# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            mkdir .venv
            pip install --upgrade --user pip
            curl https://raw.githubusercontent.com/kennethreitz/pipenv/master/get-pipenv.py | python
            pipenv run pip install -r requirements.txt
            pipenv run pip install -r requirements.dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            pipenv run pytest -s tests

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - run:
          name: Push to GemFury
          command: |
            git remote add fury https://clintontalli@git.fury.io/clintontalli/Pyrebase.git
            git push --set-upstream fury master
          filters:
            branches:
              only: master